CONFIG_NAME: 'SSC-GAN'
DATASET_NAME: 'birds'
DATA_DIR: './data_dir'
SAVE_DIR: '../output/vis'
GPU_ID: '0'
WORKERS: 4

CLASSES: 200
TIED_CODES: True

TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: '' 
    NET_D: '' 
    NET_C: ''
    BATCH_SIZE: 32
    MAX_EPOCH: 500
    HARDNEG_MAX_ITER: 1500
    SNAPSHOT_INTERVAL: 2000
    SNAPSHOT_INTERVAL_HARDNEG: 500
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    CLASSIFIER_LR: 0.001
GAN:
    DF_DIM: 64
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2
